services:
  meilisearch:
    image: getmeili/meilisearch:v1.14
    restart: always
    environment:
      MEILI_MASTER_KEY: ${GLOBAL_MEILI_KEY}
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
    healthcheck:
      test: [ "CMD", "curl", "-I", "http://127.0.0.1:7700/health" ]
      interval: 5s
      timeout: 3s
      retries: 5
