services:
  web:
    environment:
      BACKEND: "http://host.docker.internal:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  backend:
    ports:
      - "8000:8000"
    environment:
      ENV: "${ENV:-local}"
      OBB_WIZARD_BASE_URL: "http://host.docker.internal:8001"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  wizard:
    ports:
      - "8001:8000"
    environment:
      ENV: "${ENV:-local}"
      OBW_BACKEND_BASE_URL: "http://host.docker.internal:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  wizard-worker:
    environment:
      ENV: "${ENV:-local}"
      OBW_BACKEND_BASE_URL: "http://host.docker.internal:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  postgres:
    ports:
      - "5432:5432"

  minio:
    ports:
      - "9001:9001"

  meilisearch:
    ports:
      - "7700:7700"

  kafka:
    ports:
      - "9092:9092"

  mailhog:
    ports:
      - "1025:1025"

  init:
    image: alpine/curl:8.10.0
    command: 
      - 'http://backend.:8000/internal/api/v1/sign-up'
      - '-H'
      - 'Content-Type: application/json'
      - '-d'
      - '{"username":"Zs4ioltDLd","password":"Nh4PLRKPQw","email":"omnibox@qq.com"}'
    depends_on:
      backend:
        condition: service_healthy
