services:
  web:
    environment:
      BACKEND: "http://host.docker.internal:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  backend:
    ports:
      - "8000:8000"
    environment:
      ENV: "${ENV:-local}"
      OBB_WIZARD_BASE_URL: "http://host.docker.internal:8001"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  wizard:
    ports:
      - "8001:8000"
    environment:
      ENV: "${ENV:-local}"
      OBW_BACKEND_BASE_URL: "http://host.docker.internal:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  wizard-worker:
    environment:
      ENV: "${ENV:-local}"
      OBW_BACKEND_BASE_URL: "http://host.docker.internal:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
