name: Main Branch Webhook

on:
  push:
    branches:
      - main

jobs:
  webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Call webhook
        run: |
          REF="${{ github.ref_name }}"
          REF_LINK_TEXT="${{ github.ref_name }}"
          REF_LINK_URL="${{ github.server_url }}/${{ github.repository }}/tree/${{ github.ref_name }}"
          RUN_URL="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          curl "${{ secrets.DEV_WEBHOOK_URL }}/pre?run_url=$RUN_URL&ref=$REF&ref_link_text=$REF_LINK_TEXT&ref_link_url=$REF_LINK_URL" \
            -H "Authorization: Bearer ${{ secrets.DEV_WEBHOOK_API_KEY }}"
